// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'currentPath': string;
  'empty': string;
  'error': string;
  'fileEntry': string;
  'fileList': string;
  'filePickerModal': string;
  'footer': string;
  'header': string;
  'icon': string;
  'loading': string;
  'name': string;
  'pathBar': string;
}
export const cssExports: CssExports;
export default cssExports;
